### ISSUE TITLE
[improvement]> Sorting alphabetically 

### ISSUE THREAD

**Issue by fxbenard** [codepress/Transifex-Stats#1]
When several translations are 100% translated (or have the same percentage), it will be nice to create a second layer to sort them alphabetically

![the events calendar category colors - wp-translations-14-04-2014](https://cloud.githubusercontent.com/assets/802114/2695628/c01387c8-c3d8-11e3-9853-efb0e9e824a9.png)

**Comment by tobiasschutter** [comment]
I haven't been able to find the time to implement this. However I added the following filter which will allow you to control the stats ouput. 

```
$stats = apply_filters( 'cpti_transifex_stats', $stats, $project );
```

If you can make this work I am happy to accept it as a pull request :)
